# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 20:32
from __future__ import unicode_literals
from django.db import migrations


def gandalf(apps, schema_editor):
    Character = apps.get_model("lotr", "Character")
    character = Character
    character.name = 'Gandalf'
    character.save


class Migration(migrations.Migration):

    dependencies = [
        ('lotr', '0001_initial'),
    ]

    operations = [migrations.RunPython(gandalf)
    ]
